// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CopyController from "./copy_controller"
application.register("copy", CopyController)

import CountdownController from "./countdown_controller"
application.register("countdown", CountdownController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImposterRangeController from "./imposter_range_controller"
application.register("imposter-range", ImposterRangeController)

import PeekController from "./peek_controller"
application.register("peek", PeekController)

import PreventMorphController from "./prevent_morph_controller"
application.register("prevent-morph", PreventMorphController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import ToggleOnValueController from "./toggle_on_value_controller"
application.register("toggle-on-value", ToggleOnValueController)

import TurboFormController from "./turbo_form_controller"
application.register("turbo-form", TurboFormController)
